
publish_mode: editorial_workflow
media_folder: "assets/uploads" # Media files will be stored in the repo under uploads/versions

backend:
  name: git-gateway
  repo: https://github.com/sites-yari/ynsyg-capital-netlify
  branch: master # Branch to update (optional; defaults to master)
  site_domain: insignya-capital.netlify.com


collections:
  #- name: "posts"
  #  label: "Posts"
  #  folder: "_posts"
  #  create: true
  #  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #  fields:
  #    - { label: "Titulo", name: "title", widget: "string" }
  #    - { label: "Classe", name: "class", widget: "hidden", default: "test-post" }  
  #    - { label: "Data de publicação", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma" }
  #    - { label: "Genero de Post", name: "categoria",  widget: "select", options: [ " ", "rip"] }

#====================| POSTS |===================================================|  
  - name: "read-me"
    label: "Instruções"
    folder: "_posts"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "READ ME", name: "body", widget: "markdown" }

  - name: "equipa"
    label: "Equipa"
    folder: "_posts/equipa"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout" , widget: "hidden", default: "post" }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Class", name: "classe", widget: "select", options: [ " ", "Trabalhador"] }  
      - { label: "Imagem", name: "background_image_path", widget: "image" }
      - { label: "Genero de Post", name: "post_category", widget: "hidden", default: "equipa" }
      - { label: "Categoria", name: "categoria", widget: "select", options: [ " ", "executivo" , "analista" , "consultivo"] }
      - { label: "Nome da Imagem", name: "nome-imagem", widget: "string" }
      - { label: "Cargo", name: "cargo", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Descricao", name: "body", widget: "markdown" }

  - name: "portfolios"
    label: "Portfolios"
    folder: "_posts/portfolios"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout" , widget: "hidden", default: "portfolio" }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Class", name: "classe", widget: "hidden", default: "Trabalhador" }
      - { label: "imagem de Esterior", name: "fora_image_path", widget: "image" }
      - { label: "imagem de interior", name: "dentro_image_path", widget: "image" }
      - { label: "Categoria", name: "category", widget: "hidden", default: "portfolios" }
      - { label: "Nome da Imagem", name: "nome-imagem", widget: "string" }
      - { label: "Website", name: "website", widget: "string" }
      - { label: "Sector", name: "sector", widget: "string" }
      - { label: "Tipo de Operacoes", name: "tipo-de-operacao", widget: "string" }
      - { label: "Ano", name: "data", widget: "string" }
      - { label: "Vendas", name: "vendas", widget: "string" }
      - { label: "CEO", name: "CEO", widget: "string" }
      - { label: "Descricao", name: "descricao", widget: "string" }
#|=====================| DATA |====================================================|
  - name: "data"
    label: "Data"
    editor:
      preview: true
    files:
      #---| INDEX |---
      - name: "pagina-index"
        label: "Pagina de Inicio"
        file: "_data/pagina-index.yml"
        description: Everything needed for the index
        fields:
          - label: "Quem somos" #quem-somos
            name: quem_somos
            widget: "object"
            fields:
              - { label: "Sobre 1", name: "sobre1", widget: "string" }
              - { label: "Sobre 2", name: "sobre2", widget: "string" }
          - label: "Private Equity" #Private-equity
            name: private_equity
            widget: "object"
            fields:
              - { label: "Descrição", name: "texto_inicial", wdiget: "markdown" }
              - { label: "Sociedade Gestora", name: "sociedade", widget: "markdown" }
              - label: "Insignya FRE"
                name: fre
                widget: "object"
                fields:
                  - { label: "Drescrição sobre insignya FRE", name: "texto", widget: "markdown" }
                  - { label: "Tipo de Operações", name: "tipo_operacoes", widget: "string" }
                  - { label: "Empresas Alvo", name: "empresas_alvo", widget: "string" }
                  - { label: "Setores Alvo", name: "setores_alvo", widget: "string" }
                  - { label: "Estratégia de Investimento", name: "estrategia_invest", widget: "string" }
                  - { label: "Duração prevista", name: "duracao", widget: "string" }
                  - { label: "Nota", name: "nota", widget: "string" }
          - label: "Corporate Finance" #Corporate-finance
            name: corporate_finance
            widget: "object"
            fields:
              - { label: "Descrição", name: "texto_inicial", widget: "markdown" }
              - label: "Fusão e Aquisição"
                name: fusao_aquisicao
                widget: "object"
                fields:
                  - { label: "Descrição sobre Fusão e Aquisição", name: "texto", widget: "markdown" }
                  - label: "Lista de operações"
                    name: "lista"
                    widget: "list" 
                    fields:
                      - { label: "paragrafo", name: "text", widget: "string" }
              - { label: "Capital e Divida", name: "capital_divida", widget: "markdown" }
              - label: "Assessoria Financeira"
                name: assessoria_financeira
                widget: "object"
                fields:
                  - { label: "Drescrição sobre Assessoria", name: "texto", widget: "markdown" }
                  - label: "Lista de assessoria"
                    name: "lista"
                    widget: "list" 
                    fields:
                      - { label: "Paragrafo", name: "text", widget: "string" }
          - label: "Contactos" #contactos
            name: contactos
            widget: "object"
            fields:
              - { label: "Rua", name: "rua", widget: "string" }
              - { label: "Código Postal", name: "cod_postal", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Telefone", name: "telefone", widget: "string" }
          - label: "Background Images" #Imagens de background
            name: background_images
            widget: "object"
            fields:
              - { label: "Slide Insignya", name: "insignya", widget: "image" }
              - { label: "Quem somos", name: "quem_somos", widget: "image" }
              - { label: "Private Equity", name: "private_equity", widget: "image" }
              - { label: "Corporate Finance", name: "corporate_finance", widget: "image" }
              - { label: "Contactos", name: "contactos", widget: "image" }
      #---| SOBRE 1 |---
      - name: "quem-somos"
        label: "Quem Somos"
        file: "_data/quem-somos.yml"
        description: Descrição de quem somos
        fields:
          - label: "Informação"
            name: info
            widget: "list"
            fields:
              - { label: "Tema", name: "tema", widget: "string" }
              - { label: "Descrição do tema", name: "texto", widget: "markdown" }
          - { label: "Imagem de fundo", name: "background_image", widget: "image" }
      #---| SOBRE 2 |---
      - name: "valores"
        label: "Valores"
        file: "_data/valores.yml"
        description: Descrição dos Valores
        fields:
          - label: "Informação"
            name: info
            widget: "list"
            fields:
              - { label: "Tema", name: "tema", widget: "string" }
              - { label: "Descrição do tema", name: "texto", widget: "markdown" }
          - { label: "Imagem de fundo", name: "background_image", widget: "image" }
      #---| FAQ |---
      - name: "footer-pages"
        label: "FAQ"
        file: "_data/footer-pages.yml"
        description: questões FAQ 
        fields:
          - label: "faq"
            name: faq
            widget: "object"
            fields:
              - label: "sobre"
                name: sobre
                widget: "list"
                fields:
                  - { label: "Pergunta", name: "pergunta", widget: "string" }
                  - { label: "Resposta", name: "resposta", widget: "markdown" }
      #---| RECRUTAMENTO |---
      - name: "recrutamento"
        label: "Recrutamento"
        file: "_data/recrutamento.yml"
        description: Informação sobre o recrutamento
        fields:
          - label: "Informação"
            name: info
            widget: "list"
            fields:
              - { label: "Tema", name: "tema", widget: "string" }
          - { label: "Imagem de fundo", name: "background_image", widget: "image" }
      #---| TERMOS-USO |---
      - name: "termos-uso"
        label: "Termos de Uso"
        file: "_data/termos-uso.yml"
        description: Descrição sobre os termos de uso
        fields:
          - { label: "Descrição do uso", name: "uso", widget: "markdown" }
          - label: "Informação"
            name: temas
            widget: "list"
            fields:
              - { label: "Titulo", name: "titulo", widget: "string" }
              - { label: "Descrição do titulo", name: "texto", widget: "markdown" }





